### PR TITLE
Pictures(Update).java

### PR DESCRIPTION
**Pull request by BlackDiamond18**
kraken hat
background
skull

background1
background2

betterbackground
background1
background2

background
heart
smallship
bigship
bunkerrock
cannon
deck
siren
rock1
rock2
rock3
rock4

### CODE REVIEW

**Comment by CullenStewart-Burger** [comment]
hat

**Comment by CullenStewart-Burger** [comment]
kraken

**Comment by CullenStewart-Burger** [comment]
@BlackDiamond18 is this pull request still necessary, or may I close it?

**Comment by BlackDiamond18** [comment]
I think you can close it

**Pull request closed without merging**
